---
title: "Forecasting worksheet"
author: "Christopher C. Smith"
format: html
editor: visual
---

# Comprehensive asset screening and forecasting worksheet

To screen assets based on the last available prices, simply render this worksheet.

```{r message=FALSE}
library(tidyverse)
library(tidyquant)
library(revertR)
options(scipen = 999)
```

## S&P 500

```{r message=FALSE, warning=FALSE}
# Fetch and prep S&P 500 data
tickers <- tq_index("SP500",use_fallback=TRUE) %>% filter(symbol != "-") %>% pull(symbol)
df <- prep_data_for_forecasting(tickers, include_today=FALSE)

# Forecast returns
data(sp500_ds_plotdata, package="revertR")
sp500_forecasts <- analyze_data(df, ds_plotdata, "moving_average_z_score_stratum", "diff_z_score_stratum")

#Classify and filter double strat results
classify_investment_thesis(sp500_forecasts) %>%
  group_by(type) %>%
  arrange(desc(average_expected_return)) %>%
  filter(row_number()<4) %>%
  select(symbol,average_expected_return,type) %>%
  print()
```

## S&P 600

```{r}
# Fetch and prep S&P 600 data
tickers <- tq_index("SP600",use_fallback=TRUE) %>% filter(symbol != "-") %>% pull(symbol)
df <- prep_data_for_forecasting(tickers, include_today=FALSE)

# Forecast returns using the combo of both indicators
data("sp600_ds_plotdata", package="revertR")
sp600_forecasts <- analyze_data(df, ds_plotdata, "moving_average_z_score_stratum", "diff_z_score_stratum")

#Classify and filter double strat results
classify_investment_thesis(sp600_forecasts) %>%
  group_by(type) %>%
  arrange(desc(average_expected_return)) %>%
  filter(row_number()<4) %>%
  select(symbol,average_expected_return,type) %>%
  print()
```

## Sector ETFs

```{r}
# Fetch and prep sectors data
tickers <- c("XLRE","XLY","XLI","XLB","XLE","XLF","XLP","XLV","XLU","XAR","XBI","XHB","XME","XTL","XTN","XSW","XSD","XLK","XLC","XRT","KRE","XES","XOP","KIE","XWEB","XPH","XHS","XHE")
df <- prep_data_for_forecasting(tickers, include_today=FALSE)

# Forecast returns using the combo of both indicators
data("sectors_ds_plotdata", package="revertR")
sectors_forecasts <- analyze_data(df, ds_plotdata, "moving_average_z_score_stratum", "diff_z_score_stratum")

#Classify and filter double strat results
classify_investment_thesis(sectors_forecasts) %>%
  group_by(type) %>%
  arrange(desc(average_expected_return)) %>%
  filter(row_number()<3) %>%
  select(symbol,average_expected_return,type) %>%
  print()
```

## Country ETFs

```{r}
# Fetch and prep countries data
tickers <- c("FLLA","FLEE","FLFR","FLAX","FLIN","FLKR","FLSW","FLTW","EWO","EIRL","FLMX","EWN","ARGT","ENOR","GREK","EUSA","FLSA","UAE","EIS","FLRU","EWQ","EDEN","FLCA","EWD","FLIY","FLZA","FLGB","FLAU","EWP","FLHK","EWS","FLJP","PGAL","EFNL","THD","FLGR","GXG","IDX","FLBR","EPHE","QAT","TUR","ECH","NGE","ENZL","EGPT","EWM","FLCH","PAK","EPU")
df <- prep_data_for_forecasting(tickers, include_today=FALSE)

# Forecast returns using the combo of both indicators
data("countries_ds_plotdata", package="revertR")
countries_forecasts <- analyze_data(df, ds_plotdata, "moving_average_z_score_stratum", "diff_z_score_stratum")

#Classify and filter double strat results
classify_investment_thesis(countries_forecasts) %>%
  group_by(type) %>%
  arrange(desc(average_expected_return)) %>%
  filter(row_number()<3) %>%
  select(symbol,average_expected_return,type) %>%
  print()
```

## Selected bond ETFs

```{r}
# Fetch and prep bonds data
tickers <- c("VWOB","SPSB","IAGG","HYEM","BNDX","BND","TIP","SPLB","SPIB","BSV","GBF","BIL","SPTI","VTEB","SPHY","PLW","SPTL","IGLB","IGIB","SPMB")
df <- prep_data_for_forecasting(tickers, include_today=FALSE)

# Forecast returns using the combo of both indicators
data("bonds_ds_plotdata", package="revertR")
bonds_forecasts <- analyze_data(df, ds_plotdata, "moving_average_z_score_stratum", "diff_z_score_stratum")

#Classify and filter double strat results
classify_investment_thesis(bonds_forecasts) %>%
  group_by(type) %>%
  arrange(desc(average_expected_return)) %>%
  filter(row_number()<3) %>%
  select(symbol,average_expected_return,type) %>%
  print()
```

## Commodities ETFs

```{r}
# Fetch and prep bonds data
tickers <- c("FTRI","PICK","CUT","SRUUF","SGDJ","PPLT","GLD","SLV","PALL","UGA","BNO","USO","UNG","FUE","CANE","JO","CORN","GRU","SOYB","WEAT","NIB","REMX","JJT","SLX","JJU","JJC","JJN","DBE","GSG","DBB","BCI","DBA")
df <- prep_data_for_forecasting(tickers, include_today=FALSE)

# Forecast returns using the combo of both indicators
data("commodities_ds_plotdata", package="revertR")
commodities_forecasts <- analyze_data(df, ds_plotdata, "moving_average_z_score_stratum", "diff_z_score_stratum")

#Classify and filter double strat results
classify_investment_thesis(commodities_forecasts) %>%
  group_by(type) %>%
  arrange(desc(average_expected_return)) %>%
  filter(row_number()<3) %>%
  select(symbol,average_expected_return,type) %>%
  print()
```
